# Site settings
title: Shams Blog
email: mdshamsc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  পড়াশোনা ফিন্যান্স নিয়ে কিন্তু নেশাটা ছিল ৃজনশীল কিছু করা নিয়ে। তাই কখনও প্রোগ্রামিং নিয়ে কখনও বা ছবি আঁকা নিয়ে প্রে তাম : "" # the subpath of your site, e.g. /blog/
url: "http://blog.mdshams.com" # the base hostname & protocol for your site
twitter_username: delwardesigns
github_username:  mdshams

# Build settings
markdown: kramdown

paginate: 5

author: Md. Shamsuddin

gems: [jekyll-paginate]
